/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item } from "./components/keyed-list/keyed-list";
export { Item } from "./components/keyed-list/keyed-list";
export namespace Components {
    /**
     * Renders a keyed list where each item is either a <p> or a <div>,
     * keyed by `item.id` only. The same id can therefore be a <p> in one
     * render and a <div> in the next.
     */
    interface KeyedList {
        /**
          * @default []
         */
        "items": Item[];
    }
}
declare global {
    /**
     * Renders a keyed list where each item is either a <p> or a <div>,
     * keyed by `item.id` only. The same id can therefore be a <p> in one
     * render and a <div> in the next.
     */
    interface HTMLKeyedListElement extends Components.KeyedList, HTMLStencilElement {
    }
    var HTMLKeyedListElement: {
        prototype: HTMLKeyedListElement;
        new (): HTMLKeyedListElement;
    };
    interface HTMLElementTagNameMap {
        "keyed-list": HTMLKeyedListElement;
    }
}
declare namespace LocalJSX {
    /**
     * Renders a keyed list where each item is either a <p> or a <div>,
     * keyed by `item.id` only. The same id can therefore be a <p> in one
     * render and a <div> in the next.
     */
    interface KeyedList {
        /**
          * @default []
         */
        "items"?: Item[];
    }
    interface IntrinsicElements {
        "keyed-list": KeyedList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Renders a keyed list where each item is either a <p> or a <div>,
             * keyed by `item.id` only. The same id can therefore be a <p> in one
             * render and a <div> in the next.
             */
            "keyed-list": LocalJSX.IntrinsicElements["keyed-list"] & JSXBase.HTMLAttributes<HTMLKeyedListElement>;
        }
    }
}
